name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  nuget-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x.x

      - name: Publish NekoSpace.Toolkit.HostedServices
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/NekoSpace.Toolkit.HostedServices/NekoSpace.Toolkit.HostedServices.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
